from MeguBot import (DEV_USERS, SUDO_USERS, SUPPORT_USERS, FROG_USERS,
                          WHITELIST_USERS, telethn)

IMMUNE_USERS = SUDO_USERS + WHITELIST_USERS + SUPPORT_USERS + FROG_USERS + DEV_USERS

IMMUNE_USERS = list(SUDO_USERS) + list(WHITELIST_USERS) + list(
    SUPPORT_USERS) + list(FROG_USERS) + list(DEV_USERS)
